//
//  Rates.swift
//  CurrencyConverterCalculator
//
//  Created by Mustafa Ozhan on 09/08/2019.
//  Copyright © 2019 Mustafa Ozhan. All rights reserved.
//

import Foundation

class Rates: Codable {
    var aed: Double?
    var afn: Double?
    var all: Double?
    var amd: Double?
    var ang: Double?
    var aoa: Double?
    var ars: Double?
    var aud: Double?
    var awg: Double?
    var azn: Double?
    var bam: Double?
    var bbd: Double?
    var bdt: Double?
    var bgn: Double?
    var bhd: Double?
    var bif: Double?
    var bmd: Double?
    var bnd: Double?
    var bob: Double?
    var brl: Double?
    var bsd: Double?
    var btc: Double?
    var btn: Double?
    var bwp: Double?
    var byn: Double?
    var byr: Double?
    var bzd: Double?
    var cad: Double?
    var cdf: Double?
    var chf: Double?
    var clf: Double?
    var clp: Double?
    var cny: Double?
    var cop: Double?
    var crc: Double?
    var cuc: Double?
    var cup: Double?
    var cve: Double?
    var czk: Double?
    var djf: Double?
    var dkk: Double?
    var dop: Double?
    var dzd: Double?
    var egp: Double?
    var ern: Double?
    var etb: Double?
    var eur: Double?
    var fjd: Double?
    var fkp: Double?
    var gbp: Double?
    var gel: Double?
    var ggp: Double?
    var ghs: Double?
    var gip: Double?
    var gmd: Double?
    var gnf: Double?
    var gtq: Double?
    var gyd: Double?
    var hkd: Double?
    var hnl: Double?
    var hrk: Double?
    var htg: Double?
    var huf: Double?
    var idr: Double?
    var ils: Double?
    var imp: Double?
    var inr: Double?
    var iqd: Double?
    var irr: Double?
    var isk: Double?
    var jep: Double?
    var jmd: Double?
    var jod: Double?
    var jpy: Double?
    var kes: Double?
    var kgs: Double?
    var khr: Double?
    var kmf: Double?
    var kpw: Double?
    var krw: Double?
    var kwd: Double?
    var kyd: Double?
    var kzt: Double?
    var lak: Double?
    var lbp: Double?
    var lkr: Double?
    var lrd: Double?
    var lsl: Double?
    var ltl: Double?
    var lvl: Double?
    var lyd: Double?
    var mad: Double?
    var mdl: Double?
    var mga: Double?
    var mkd: Double?
    var mmk: Double?
    var mnt: Double?
    var mop: Double?
    var mro: Double?
    var mur: Double?
    var mvr: Double?
    var mwk: Double?
    var mxn: Double?
    var myr: Double?
    var mzn: Double?
    var nad: Double?
    var ngn: Double?
    var nio: Double?
    var nok: Double?
    var npr: Double?
    var nzd: Double?
    var omr: Double?
    var pab: Double?
    var pen: Double?
    var pgk: Double?
    var php: Double?
    var pkr: Double?
    var pln: Double?
    var pyg: Double?
    var qar: Double?
    var ron: Double?
    var rsd: Double?
    var rub: Double?
    var rwf: Double?
    var sar: Double?
    var sbd: Double?
    var scr: Double?
    var sdg: Double?
    var sek: Double?
    var sgd: Double?
    var shp: Double?
    var sll: Double?
    var sos: Double?
    var srd: Double?
    var std: Double?
    var svc: Double?
    var syp: Double?
    var szl: Double?
    var thb: Double?
    var tjs: Double?
    var tmt: Double?
    var tnd: Double?
    var top: Double?
    var `try`: Double?
    var ttd: Double?
    var twd: Double?
    var tzs: Double?
    var uah: Double?
    var ugx: Double?
    var usd: Double?
    var uyu: Double?
    var uzs: Double?
    var vef: Double?
    var vnd: Double?
    var vuv: Double?
    var wst: Double?
    var xaf: Double?
    var xag: Double?
    var xau: Double?
    var xcd: Double?
    var xdr: Double?
    var xof: Double?
    var xpf: Double?
    var yer: Double?
    var zar: Double?
    var zmk: Double?
    var zmw: Double?
    var zwl: Double?
}
